In [11]:
import pandas as pd

In [12]:
# Read cleaned csv
cleaned_df = pd.read_csv('merged_df_cleaned_040323.csv', index_col= False)
cleaned_df.head()

,responder_id,birth_year,gender,industry_desc,occupation_desc,organization_size,manage_others,household,years_at_job,metro_or_regional,...,productivity_remote_vs_office,inperson_hours__commuting,inperson_hours__working,inperson_hours__personal_family_time,inperson_hours_domestic_responsibilities,remote_hours_commuting,remote_hours_working,remote_hours_personal_family_time,remote_hours_domestic_responsibilities,commute_time_difference
0,0,1972,Female,Other,Clerical and administrative,Between 20 and 199,No,Couple with no dependent children,More than 5 years,Regional,...,much more productive,2.0,8.0,2.0,2.0,0.5,8.0,3.5,2.0,1.5
1,1,1972,Male,Other,Managers,Between 1 and 4,Yes,Couple with dependent children,More than 5 years,Metro,...,less productive,2.0,7.0,3.0,3.0,0.0,7.0,3.0,3.0,2.0
2,2,1982,Male,Other,Managers,More than 200,Yes,One parent family with dependent children,More than 5 years,Metro,...,less productive,6.0,1.0,6.0,5.0,5.0,2.0,7.0,7.0,1.0
3,3,1987,Female,"Professional, Scientific and Technical Services",Professionals,Between 20 and 199,No,Couple with dependent children,Between 1 and 5 years,Metro,...,same productivity,1.0,9.0,1.0,2.0,0.0,9.0,3.0,2.0,1.0
4,4,1991,Male,Other,Managers,Between 5 and 19,Yes,Couple with no dependent children,More than 5 years,Metro,...,more productive,1.0,8.0,3.5,2.0,0.0,6.0,4.0,3.0,1.0

In [13]:
# create csv for respondents table
respondents_df = cleaned_df[['responder_id', 'birth_year', 'gender',
    'industry_desc', 'occupation_desc', 'manage_others',
    'household', 'years_at_job', 'metro_or_regional']].copy()
respondents_df.head()

,responder_id,birth_year,gender,industry_desc,occupation_desc,manage_others,household,years_at_job,metro_or_regional
0,0,1972,Female,Other,Clerical and administrative,No,Couple with no dependent children,More than 5 years,Regional
1,1,1972,Male,Other,Managers,Yes,Couple with dependent children,More than 5 years,Metro
2,2,1982,Male,Other,Managers,Yes,One parent family with dependent children,More than 5 years,Metro
3,3,1987,Female,"Professional, Scientific and Technical Services",Professionals,No,Couple with dependent children,Between 1 and 5 years,Metro
4,4,1991,Male,Other,Managers,Yes,Couple with no dependent children,More than 5 years,Metro

In [15]:
# Save respondents dataframe as csv file
respondents_df.to_csv("respondents.csv", index=False)

In [16]:
# create csv for orginizational data table
orginizational_data_df = cleaned_df[['responder_id', 'organization_size', 'org_encouraged_rw', 
        'org_prepared_for_rw', 'rw_is_common_at_org', 'rw_permission_is_attainable', 
        'rw_collaboration_easy', 'if_no_covid_employer_encourage_rw',
        'if_no_covid_employer_support_rw', 'if_no_covid_i_would_have_choice_about_rw']].copy()
orginizational_data_df.head()

,responder_id,organization_size,org_encouraged_rw,org_prepared_for_rw,rw_is_common_at_org,rw_permission_is_attainable,rw_collaboration_easy,if_no_covid_employer_encourage_rw,if_no_covid_employer_support_rw,if_no_covid_i_would_have_choice_about_rw
0,0,Between 20 and 199,Strongly agree,Somewhat agree,Somewhat agree,Strongly agree,Somewhat agree,Somewhat disagree,Somewhat disagree,Strongly disagree
1,1,Between 1 and 4,Somewhat agree,Somewhat agree,Somewhat agree,Somewhat agree,Somewhat agree,Somewhat agree,Somewhat agree,Somewhat agree
2,2,More than 200,Neither agree nor disagree,Somewhat agree,Somewhat agree,Neither agree nor disagree,Somewhat agree,Somewhat agree,Somewhat agree,Somewhat agree
3,3,Between 20 and 199,Strongly agree,Somewhat disagree,Somewhat agree,Strongly agree,Strongly agree,Somewhat agree,Strongly agree,Somewhat agree
4,4,Between 5 and 19,Somewhat disagree,Somewhat agree,Strongly agree,Somewhat disagree,Somewhat agree,Strongly disagree,Strongly disagree,Strongly disagree

In [17]:
# Save orginizational_data dataframe as csv file
orginizational_data_df.to_csv("orginizational_data.csv", index=False)

In [18]:
# create csv for time management data table
time_management_df = cleaned_df[['responder_id', 'rw_percentage_2020', 
    'preferred_rw_percentage_2020', 'preferred_rw_percentage_future', 
    'productivity_remote_vs_office', 'inperson_hours__commuting', 
    'inperson_hours__working', 'inperson_hours__personal_family_time', 
    'inperson_hours_domestic_responsibilities','remote_hours_commuting',
    'remote_hours_working', 'remote_hours_personal_family_time',
    'remote_hours_domestic_responsibilities', 'commute_time_difference']].copy()
time_management_df.head()

,responder_id,rw_percentage_2020,preferred_rw_percentage_2020,preferred_rw_percentage_future,productivity_remote_vs_office,inperson_hours__commuting,inperson_hours__working,inperson_hours__personal_family_time,inperson_hours_domestic_responsibilities,remote_hours_commuting,remote_hours_working,remote_hours_personal_family_time,remote_hours_domestic_responsibilities,commute_time_difference
0,0,4-5 days,4-5 days,4-5 days,much more productive,2.0,8.0,2.0,2.0,0.5,8.0,3.5,2.0,1.5
1,1,1-2 days,1-2 days,1-2 days,less productive,2.0,7.0,3.0,3.0,0.0,7.0,3.0,3.0,2.0
2,2,2-3 days,3-4 days,3-4 days,less productive,6.0,1.0,6.0,5.0,5.0,2.0,7.0,7.0,1.0
3,3,4-5 days,4-5 days,4-5 days,same productivity,1.0,9.0,1.0,2.0,0.0,9.0,3.0,2.0,1.0
4,4,4-5 days,4-5 days,3-4 days,more productive,1.0,8.0,3.5,2.0,0.0,6.0,4.0,3.0,1.0

In [19]:
# Save time management dataframe as csv file
time_management_df.to_csv("time_management.csv", index=False)